//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from erebus.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class erebusParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, WS=6, COMMENT=7, SEMI=8, PLUS=9, 
		MINUS=10, MULT=11, DIV=12, EQUAL=13, ASSIGN=14, NOTEQUAL=15, GT=16, LT=17, 
		GTEQ=18, LTEQ=19, AND=20, OR=21, NOT=22, CONTAINS=23, LPAREN=24, RPAREN=25, 
		LBRACKET=26, RBRACKET=27, BLOCK_OPEN=28, BLOCK_CLOSE=29, TRUE=30, FALSE=31, 
		POLICY=32, NUMBER=33, ID=34, STRING=35;
	public const int
		RULE_compilationUnit = 0, RULE_statement = 1, RULE_function = 2, RULE_bodystmt = 3, 
		RULE_printstmt = 4, RULE_assignstmt = 5, RULE_ifstmt = 6, RULE_funcname = 7, 
		RULE_value = 8, RULE_conditionExpr = 9, RULE_logicalExpr = 10, RULE_comparisonExpr = 11, 
		RULE_cmpOperand = 12, RULE_logicalEntity = 13, RULE_opExpression = 14, 
		RULE_cmpOp = 15, RULE_logicOp = 16, RULE_numericTerm = 17, RULE_api = 18, 
		RULE_list = 19, RULE_array = 20;
	public static readonly string[] ruleNames = {
		"compilationUnit", "statement", "function", "bodystmt", "printstmt", "assignstmt", 
		"ifstmt", "funcname", "value", "conditionExpr", "logicalExpr", "comparisonExpr", 
		"cmpOperand", "logicalEntity", "opExpression", "cmpOp", "logicOp", "numericTerm", 
		"api", "list", "array"
	};

	private static readonly string[] _LiteralNames = {
		null, "'func'", "','", "'console.log('", "'let'", "'if'", null, null, 
		"';'", "'+'", "'-'", "'*'", "'/'", "'=='", "'='", "'!='", "'>'", "'<'", 
		"'>='", "'<='", "'&&'", "'||'", "'!'", "'.includes'", "'('", "')'", "'['", 
		"']'", "'{'", "'}'", "'true'", "'false'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "WS", "COMMENT", "SEMI", "PLUS", "MINUS", 
		"MULT", "DIV", "EQUAL", "ASSIGN", "NOTEQUAL", "GT", "LT", "GTEQ", "LTEQ", 
		"AND", "OR", "NOT", "CONTAINS", "LPAREN", "RPAREN", "LBRACKET", "RBRACKET", 
		"BLOCK_OPEN", "BLOCK_CLOSE", "TRUE", "FALSE", "POLICY", "NUMBER", "ID", 
		"STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "erebus.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static erebusParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public erebusParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public erebusParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CompilationUnitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(erebusParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterCompilationUnit(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitCompilationUnit(this);
		}
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 42;
				statement();
				}
				}
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 48;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			function();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FuncnameContext funcname() {
			return GetRuleContext<FuncnameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(erebusParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLOCK_OPEN() { return GetToken(erebusParser.BLOCK_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLOCK_CLOSE() { return GetToken(erebusParser.BLOCK_CLOSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(erebusParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(erebusParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BodystmtContext[] bodystmt() {
			return GetRuleContexts<BodystmtContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BodystmtContext bodystmt(int i) {
			return GetRuleContext<BodystmtContext>(i);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 4, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			Match(T__0);
			State = 53;
			funcname();
			State = 54;
			Match(LPAREN);
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 55;
				Match(ID);
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__1) {
					{
					{
					State = 56;
					Match(T__1);
					State = 57;
					Match(ID);
					}
					}
					State = 62;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 65;
			Match(RPAREN);
			State = 66;
			Match(BLOCK_OPEN);
			State = 70;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__2) | (1L << T__3) | (1L << T__4))) != 0)) {
				{
				{
				State = 67;
				bodystmt();
				}
				}
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 73;
			Match(BLOCK_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BodystmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IfstmtContext ifstmt() {
			return GetRuleContext<IfstmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintstmtContext printstmt() {
			return GetRuleContext<PrintstmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignstmtContext assignstmt() {
			return GetRuleContext<AssignstmtContext>(0);
		}
		public BodystmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bodystmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterBodystmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitBodystmt(this);
		}
	}

	[RuleVersion(0)]
	public BodystmtContext bodystmt() {
		BodystmtContext _localctx = new BodystmtContext(Context, State);
		EnterRule(_localctx, 6, RULE_bodystmt);
		try {
			State = 78;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75;
				ifstmt();
				}
				break;
			case T__2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 76;
				printstmt();
				}
				break;
			case T__3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 77;
				assignstmt();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintstmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(erebusParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public PrintstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_printstmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterPrintstmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitPrintstmt(this);
		}
	}

	[RuleVersion(0)]
	public PrintstmtContext printstmt() {
		PrintstmtContext _localctx = new PrintstmtContext(Context, State);
		EnterRule(_localctx, 8, RULE_printstmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			Match(T__2);
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LBRACKET) | (1L << NUMBER) | (1L << ID) | (1L << STRING))) != 0)) {
				{
				State = 81;
				value();
				}
			}

			State = 84;
			Match(RPAREN);
			State = 85;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignstmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(erebusParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(erebusParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(erebusParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ApiContext api() {
			return GetRuleContext<ApiContext>(0);
		}
		public AssignstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignstmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterAssignstmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitAssignstmt(this);
		}
	}

	[RuleVersion(0)]
	public AssignstmtContext assignstmt() {
		AssignstmtContext _localctx = new AssignstmtContext(Context, State);
		EnterRule(_localctx, 10, RULE_assignstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			Match(T__3);
			State = 88;
			Match(ID);
			State = 89;
			Match(ASSIGN);
			State = 92;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 90;
				value();
				}
				break;
			case 2:
				{
				State = 91;
				api();
				}
				break;
			}
			State = 94;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfstmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(erebusParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ConditionExprContext conditionExpr() {
			return GetRuleContext<ConditionExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLOCK_OPEN() { return GetToken(erebusParser.BLOCK_OPEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POLICY() { return GetToken(erebusParser.POLICY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(erebusParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLOCK_CLOSE() { return GetToken(erebusParser.BLOCK_CLOSE, 0); }
		public IfstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifstmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterIfstmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitIfstmt(this);
		}
	}

	[RuleVersion(0)]
	public IfstmtContext ifstmt() {
		IfstmtContext _localctx = new IfstmtContext(Context, State);
		EnterRule(_localctx, 12, RULE_ifstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(T__4);
			State = 97;
			Match(LPAREN);
			State = 98;
			conditionExpr();
			State = 99;
			Match(RPAREN);
			State = 100;
			Match(BLOCK_OPEN);
			State = 101;
			Match(POLICY);
			State = 102;
			Match(SEMI);
			State = 103;
			Match(BLOCK_CLOSE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FuncnameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(erebusParser.ID, 0); }
		public FuncnameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funcname; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterFuncname(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitFuncname(this);
		}
	}

	[RuleVersion(0)]
	public FuncnameContext funcname() {
		FuncnameContext _localctx = new FuncnameContext(Context, State);
		EnterRule(_localctx, 14, RULE_funcname);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(erebusParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(erebusParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(erebusParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ListContext list() {
			return GetRuleContext<ListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 16, RULE_value);
		try {
			State = 112;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 107;
				Match(ID);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 108;
				Match(NUMBER);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 109;
				Match(STRING);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 110;
				list();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 111;
				array();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		public ConditionExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditionExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterConditionExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitConditionExpr(this);
		}
	}

	[RuleVersion(0)]
	public ConditionExprContext conditionExpr() {
		ConditionExprContext _localctx = new ConditionExprContext(Context, State);
		EnterRule(_localctx, 18, RULE_conditionExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114;
			logicalExpr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(erebusParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext[] logicalExpr() {
			return GetRuleContexts<LogicalExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr(int i) {
			return GetRuleContext<LogicalExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonExprContext comparisonExpr() {
			return GetRuleContext<ComparisonExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(erebusParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalEntityContext logicalEntity() {
			return GetRuleContext<LogicalEntityContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicOpContext logicOp() {
			return GetRuleContext<LogicOpContext>(0);
		}
		public LogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterLogicalExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitLogicalExpr(this);
		}
	}

	[RuleVersion(0)]
	public LogicalExprContext logicalExpr() {
		return logicalExpr(0);
	}

	private LogicalExprContext logicalExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		LogicalExprContext _localctx = new LogicalExprContext(Context, _parentState);
		LogicalExprContext _prevctx = _localctx;
		int _startState = 20;
		EnterRecursionRule(_localctx, 20, RULE_logicalExpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				State = 117;
				Match(NOT);
				State = 118;
				logicalExpr(4);
				}
				break;
			case 2:
				{
				State = 119;
				comparisonExpr();
				}
				break;
			case 3:
				{
				State = 120;
				Match(LPAREN);
				State = 121;
				logicalExpr(0);
				State = 122;
				Match(RPAREN);
				}
				break;
			case 4:
				{
				State = 124;
				logicalEntity();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 133;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new LogicalExprContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_logicalExpr);
					State = 127;
					if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
					State = 128;
					logicOp();
					State = 129;
					logicalExpr(6);
					}
					} 
				}
				State = 135;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ComparisonExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CmpOperandContext[] cmpOperand() {
			return GetRuleContexts<CmpOperandContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CmpOperandContext cmpOperand(int i) {
			return GetRuleContext<CmpOperandContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CmpOpContext cmpOp() {
			return GetRuleContext<CmpOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONTAINS() { return GetToken(erebusParser.CONTAINS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(erebusParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		public ComparisonExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparisonExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterComparisonExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitComparisonExpr(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonExprContext comparisonExpr() {
		ComparisonExprContext _localctx = new ComparisonExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_comparisonExpr);
		try {
			State = 146;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 136;
				cmpOperand();
				State = 137;
				cmpOp();
				State = 138;
				cmpOperand();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 140;
				cmpOperand();
				State = 141;
				Match(CONTAINS);
				State = 142;
				Match(LPAREN);
				State = 143;
				cmpOperand();
				State = 144;
				Match(RPAREN);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CmpOperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpExpressionContext opExpression() {
			return GetRuleContext<OpExpressionContext>(0);
		}
		public CmpOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cmpOperand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterCmpOperand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitCmpOperand(this);
		}
	}

	[RuleVersion(0)]
	public CmpOperandContext cmpOperand() {
		CmpOperandContext _localctx = new CmpOperandContext(Context, State);
		EnterRule(_localctx, 24, RULE_cmpOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			opExpression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalEntityContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(erebusParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(erebusParser.FALSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(erebusParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(erebusParser.STRING, 0); }
		public LogicalEntityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalEntity; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterLogicalEntity(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitLogicalEntity(this);
		}
	}

	[RuleVersion(0)]
	public LogicalEntityContext logicalEntity() {
		LogicalEntityContext _localctx = new LogicalEntityContext(Context, State);
		EnterRule(_localctx, 26, RULE_logicalEntity);
		int _la;
		try {
			State = 153;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TRUE:
			case FALSE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 150;
				_la = TokenStream.LA(1);
				if ( !(_la==TRUE || _la==FALSE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 151;
				Match(ID);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 3);
				{
				State = 152;
				Match(STRING);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(erebusParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OpExpressionContext[] opExpression() {
			return GetRuleContexts<OpExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpExpressionContext opExpression(int i) {
			return GetRuleContext<OpExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumericTermContext numericTerm() {
			return GetRuleContext<NumericTermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(erebusParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(erebusParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(erebusParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(erebusParser.MINUS, 0); }
		public OpExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_opExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterOpExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitOpExpression(this);
		}
	}

	[RuleVersion(0)]
	public OpExpressionContext opExpression() {
		return opExpression(0);
	}

	private OpExpressionContext opExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		OpExpressionContext _localctx = new OpExpressionContext(Context, _parentState);
		OpExpressionContext _prevctx = _localctx;
		int _startState = 28;
		EnterRecursionRule(_localctx, 28, RULE_opExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LPAREN:
				{
				State = 156;
				Match(LPAREN);
				State = 157;
				opExpression(0);
				State = 158;
				Match(RPAREN);
				}
				break;
			case NUMBER:
			case ID:
				{
				State = 160;
				numericTerm();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 177;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 175;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
					case 1:
						{
						_localctx = new OpExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_opExpression);
						State = 163;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 164;
						Match(MULT);
						State = 165;
						opExpression(7);
						}
						break;
					case 2:
						{
						_localctx = new OpExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_opExpression);
						State = 166;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 167;
						Match(DIV);
						State = 168;
						opExpression(6);
						}
						break;
					case 3:
						{
						_localctx = new OpExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_opExpression);
						State = 169;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 170;
						Match(PLUS);
						State = 171;
						opExpression(5);
						}
						break;
					case 4:
						{
						_localctx = new OpExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_opExpression);
						State = 172;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 173;
						Match(MINUS);
						State = 174;
						opExpression(4);
						}
						break;
					}
					} 
				}
				State = 179;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class CmpOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(erebusParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GTEQ() { return GetToken(erebusParser.GTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(erebusParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LTEQ() { return GetToken(erebusParser.LTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(erebusParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUAL() { return GetToken(erebusParser.NOTEQUAL, 0); }
		public CmpOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cmpOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterCmpOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitCmpOp(this);
		}
	}

	[RuleVersion(0)]
	public CmpOpContext cmpOp() {
		CmpOpContext _localctx = new CmpOpContext(Context, State);
		EnterRule(_localctx, 30, RULE_cmpOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << EQUAL) | (1L << NOTEQUAL) | (1L << GT) | (1L << LT) | (1L << GTEQ) | (1L << LTEQ))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(erebusParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(erebusParser.OR, 0); }
		public LogicOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterLogicOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitLogicOp(this);
		}
	}

	[RuleVersion(0)]
	public LogicOpContext logicOp() {
		LogicOpContext _localctx = new LogicOpContext(Context, State);
		EnterRule(_localctx, 32, RULE_logicOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			_la = TokenStream.LA(1);
			if ( !(_la==AND || _la==OR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumericTermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(erebusParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(erebusParser.NUMBER, 0); }
		public NumericTermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numericTerm; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterNumericTerm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitNumericTerm(this);
		}
	}

	[RuleVersion(0)]
	public NumericTermContext numericTerm() {
		NumericTermContext _localctx = new NumericTermContext(Context, State);
		EnterRule(_localctx, 34, RULE_numericTerm);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			_la = TokenStream.LA(1);
			if ( !(_la==NUMBER || _la==ID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ApiContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(erebusParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(erebusParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(erebusParser.RPAREN, 0); }
		public ApiContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_api; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterApi(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitApi(this);
		}
	}

	[RuleVersion(0)]
	public ApiContext api() {
		ApiContext _localctx = new ApiContext(Context, State);
		EnterRule(_localctx, 36, RULE_api);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			Match(ID);
			State = 187;
			Match(LPAREN);
			State = 188;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(erebusParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(erebusParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(erebusParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(erebusParser.RBRACKET, 0); }
		public ListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitList(this);
		}
	}

	[RuleVersion(0)]
	public ListContext list() {
		ListContext _localctx = new ListContext(Context, State);
		EnterRule(_localctx, 38, RULE_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			Match(LBRACKET);
			State = 191;
			Match(STRING);
			State = 196;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 192;
				Match(T__1);
				State = 193;
				Match(STRING);
				}
				}
				State = 198;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 199;
			Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(erebusParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(erebusParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(erebusParser.NUMBER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(erebusParser.RBRACKET, 0); }
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.EnterArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IerebusListener typedListener = listener as IerebusListener;
			if (typedListener != null) typedListener.ExitArray(this);
		}
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 40, RULE_array);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			Match(LBRACKET);
			State = 202;
			Match(NUMBER);
			State = 207;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 203;
				Match(T__1);
				State = 204;
				Match(NUMBER);
				}
				}
				State = 209;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 210;
			Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 10: return logicalExpr_sempred((LogicalExprContext)_localctx, predIndex);
		case 14: return opExpression_sempred((OpExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool logicalExpr_sempred(LogicalExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		}
		return true;
	}
	private bool opExpression_sempred(OpExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 6);
		case 2: return Precpred(Context, 5);
		case 3: return Precpred(Context, 4);
		case 4: return Precpred(Context, 3);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,35,213,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,1,0,5,0,44,
		8,0,10,0,12,0,47,9,0,1,0,1,0,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,5,2,59,8,
		2,10,2,12,2,62,9,2,3,2,64,8,2,1,2,1,2,1,2,5,2,69,8,2,10,2,12,2,72,9,2,
		1,2,1,2,1,3,1,3,1,3,3,3,79,8,3,1,4,1,4,3,4,83,8,4,1,4,1,4,1,4,1,5,1,5,
		1,5,1,5,1,5,3,5,93,8,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,7,
		1,7,1,8,1,8,1,8,1,8,1,8,3,8,113,8,8,1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,3,10,126,8,10,1,10,1,10,1,10,1,10,5,10,132,8,10,10,10,
		12,10,135,9,10,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,3,11,
		147,8,11,1,12,1,12,1,13,1,13,1,13,3,13,154,8,13,1,14,1,14,1,14,1,14,1,
		14,1,14,3,14,162,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,5,14,176,8,14,10,14,12,14,179,9,14,1,15,1,15,1,16,1,16,1,17,
		1,17,1,18,1,18,1,18,1,18,1,19,1,19,1,19,1,19,5,19,195,8,19,10,19,12,19,
		198,9,19,1,19,1,19,1,20,1,20,1,20,1,20,5,20,206,8,20,10,20,12,20,209,9,
		20,1,20,1,20,1,20,0,2,20,28,21,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,
		30,32,34,36,38,40,0,4,1,0,30,31,2,0,13,13,15,19,1,0,20,21,1,0,33,34,217,
		0,45,1,0,0,0,2,50,1,0,0,0,4,52,1,0,0,0,6,78,1,0,0,0,8,80,1,0,0,0,10,87,
		1,0,0,0,12,96,1,0,0,0,14,105,1,0,0,0,16,112,1,0,0,0,18,114,1,0,0,0,20,
		125,1,0,0,0,22,146,1,0,0,0,24,148,1,0,0,0,26,153,1,0,0,0,28,161,1,0,0,
		0,30,180,1,0,0,0,32,182,1,0,0,0,34,184,1,0,0,0,36,186,1,0,0,0,38,190,1,
		0,0,0,40,201,1,0,0,0,42,44,3,2,1,0,43,42,1,0,0,0,44,47,1,0,0,0,45,43,1,
		0,0,0,45,46,1,0,0,0,46,48,1,0,0,0,47,45,1,0,0,0,48,49,5,0,0,1,49,1,1,0,
		0,0,50,51,3,4,2,0,51,3,1,0,0,0,52,53,5,1,0,0,53,54,3,14,7,0,54,63,5,24,
		0,0,55,60,5,34,0,0,56,57,5,2,0,0,57,59,5,34,0,0,58,56,1,0,0,0,59,62,1,
		0,0,0,60,58,1,0,0,0,60,61,1,0,0,0,61,64,1,0,0,0,62,60,1,0,0,0,63,55,1,
		0,0,0,63,64,1,0,0,0,64,65,1,0,0,0,65,66,5,25,0,0,66,70,5,28,0,0,67,69,
		3,6,3,0,68,67,1,0,0,0,69,72,1,0,0,0,70,68,1,0,0,0,70,71,1,0,0,0,71,73,
		1,0,0,0,72,70,1,0,0,0,73,74,5,29,0,0,74,5,1,0,0,0,75,79,3,12,6,0,76,79,
		3,8,4,0,77,79,3,10,5,0,78,75,1,0,0,0,78,76,1,0,0,0,78,77,1,0,0,0,79,7,
		1,0,0,0,80,82,5,3,0,0,81,83,3,16,8,0,82,81,1,0,0,0,82,83,1,0,0,0,83,84,
		1,0,0,0,84,85,5,25,0,0,85,86,5,8,0,0,86,9,1,0,0,0,87,88,5,4,0,0,88,89,
		5,34,0,0,89,92,5,14,0,0,90,93,3,16,8,0,91,93,3,36,18,0,92,90,1,0,0,0,92,
		91,1,0,0,0,93,94,1,0,0,0,94,95,5,8,0,0,95,11,1,0,0,0,96,97,5,5,0,0,97,
		98,5,24,0,0,98,99,3,18,9,0,99,100,5,25,0,0,100,101,5,28,0,0,101,102,5,
		32,0,0,102,103,5,8,0,0,103,104,5,29,0,0,104,13,1,0,0,0,105,106,5,34,0,
		0,106,15,1,0,0,0,107,113,5,34,0,0,108,113,5,33,0,0,109,113,5,35,0,0,110,
		113,3,38,19,0,111,113,3,40,20,0,112,107,1,0,0,0,112,108,1,0,0,0,112,109,
		1,0,0,0,112,110,1,0,0,0,112,111,1,0,0,0,113,17,1,0,0,0,114,115,3,20,10,
		0,115,19,1,0,0,0,116,117,6,10,-1,0,117,118,5,22,0,0,118,126,3,20,10,4,
		119,126,3,22,11,0,120,121,5,24,0,0,121,122,3,20,10,0,122,123,5,25,0,0,
		123,126,1,0,0,0,124,126,3,26,13,0,125,116,1,0,0,0,125,119,1,0,0,0,125,
		120,1,0,0,0,125,124,1,0,0,0,126,133,1,0,0,0,127,128,10,5,0,0,128,129,3,
		32,16,0,129,130,3,20,10,6,130,132,1,0,0,0,131,127,1,0,0,0,132,135,1,0,
		0,0,133,131,1,0,0,0,133,134,1,0,0,0,134,21,1,0,0,0,135,133,1,0,0,0,136,
		137,3,24,12,0,137,138,3,30,15,0,138,139,3,24,12,0,139,147,1,0,0,0,140,
		141,3,24,12,0,141,142,5,23,0,0,142,143,5,24,0,0,143,144,3,24,12,0,144,
		145,5,25,0,0,145,147,1,0,0,0,146,136,1,0,0,0,146,140,1,0,0,0,147,23,1,
		0,0,0,148,149,3,28,14,0,149,25,1,0,0,0,150,154,7,0,0,0,151,154,5,34,0,
		0,152,154,5,35,0,0,153,150,1,0,0,0,153,151,1,0,0,0,153,152,1,0,0,0,154,
		27,1,0,0,0,155,156,6,14,-1,0,156,157,5,24,0,0,157,158,3,28,14,0,158,159,
		5,25,0,0,159,162,1,0,0,0,160,162,3,34,17,0,161,155,1,0,0,0,161,160,1,0,
		0,0,162,177,1,0,0,0,163,164,10,6,0,0,164,165,5,11,0,0,165,176,3,28,14,
		7,166,167,10,5,0,0,167,168,5,12,0,0,168,176,3,28,14,6,169,170,10,4,0,0,
		170,171,5,9,0,0,171,176,3,28,14,5,172,173,10,3,0,0,173,174,5,10,0,0,174,
		176,3,28,14,4,175,163,1,0,0,0,175,166,1,0,0,0,175,169,1,0,0,0,175,172,
		1,0,0,0,176,179,1,0,0,0,177,175,1,0,0,0,177,178,1,0,0,0,178,29,1,0,0,0,
		179,177,1,0,0,0,180,181,7,1,0,0,181,31,1,0,0,0,182,183,7,2,0,0,183,33,
		1,0,0,0,184,185,7,3,0,0,185,35,1,0,0,0,186,187,5,34,0,0,187,188,5,24,0,
		0,188,189,5,25,0,0,189,37,1,0,0,0,190,191,5,26,0,0,191,196,5,35,0,0,192,
		193,5,2,0,0,193,195,5,35,0,0,194,192,1,0,0,0,195,198,1,0,0,0,196,194,1,
		0,0,0,196,197,1,0,0,0,197,199,1,0,0,0,198,196,1,0,0,0,199,200,5,27,0,0,
		200,39,1,0,0,0,201,202,5,26,0,0,202,207,5,33,0,0,203,204,5,2,0,0,204,206,
		5,33,0,0,205,203,1,0,0,0,206,209,1,0,0,0,207,205,1,0,0,0,207,208,1,0,0,
		0,208,210,1,0,0,0,209,207,1,0,0,0,210,211,5,27,0,0,211,41,1,0,0,0,17,45,
		60,63,70,78,82,92,112,125,133,146,153,161,175,177,196,207
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
