//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Scripts/Grammar/erebus.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IerebusListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class erebusBaseListener : IerebusListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] erebusParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] erebusParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] erebusParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] erebusParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] erebusParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] erebusParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.bodystmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBodystmt([NotNull] erebusParser.BodystmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.bodystmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBodystmt([NotNull] erebusParser.BodystmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.printstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstmt([NotNull] erebusParser.PrintstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.printstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstmt([NotNull] erebusParser.PrintstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.assignstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignstmt([NotNull] erebusParser.AssignstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.assignstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignstmt([NotNull] erebusParser.AssignstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] erebusParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] erebusParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] erebusParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] erebusParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.conditionExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionExpr([NotNull] erebusParser.ConditionExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.conditionExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionExpr([NotNull] erebusParser.ConditionExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpr([NotNull] erebusParser.LogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpr([NotNull] erebusParser.LogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.comparisonExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonExpr([NotNull] erebusParser.ComparisonExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.comparisonExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonExpr([NotNull] erebusParser.ComparisonExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.cmpOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmpOperand([NotNull] erebusParser.CmpOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.cmpOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmpOperand([NotNull] erebusParser.CmpOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.logicalEntity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalEntity([NotNull] erebusParser.LogicalEntityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.logicalEntity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalEntity([NotNull] erebusParser.LogicalEntityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.opExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpExpression([NotNull] erebusParser.OpExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.opExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpExpression([NotNull] erebusParser.OpExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.cmpOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmpOp([NotNull] erebusParser.CmpOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.cmpOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmpOp([NotNull] erebusParser.CmpOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.logicOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicOp([NotNull] erebusParser.LogicOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.logicOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicOp([NotNull] erebusParser.LogicOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.numericTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericTerm([NotNull] erebusParser.NumericTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.numericTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericTerm([NotNull] erebusParser.NumericTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] erebusParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] erebusParser.FuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] erebusParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] erebusParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.api"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterApi([NotNull] erebusParser.ApiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.api"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitApi([NotNull] erebusParser.ApiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] erebusParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] erebusParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="erebusParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] erebusParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="erebusParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] erebusParser.ArrayContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
